/**
 * Schema Validator — 基于 Concept 定义校验实例字段
 */

import fs from "fs/promises";
import { schemaPath, isValidId } from "./config";
import type { ConceptSchema, ConceptField } from "./types";

export function validateInstance(
	fields: Record<string, unknown>,
	schema: ConceptSchema
): void {
	const errors: string[] = [];
	const schemaFieldNames = new Set(schema.fields.map((f) => f.name));

	// 严格模式：字段必须在 schema 中定义，或声明为扩展字段（以 "_ext_" 前缀标识）
	for (const key of Object.keys(fields)) {
		if (!schemaFieldNames.has(key) && !key.startsWith("_ext_")) {
			errors.push(`字段 "${key}" 不在 schema 定义中，如需写入额外信息请使用 "_ext_" 前缀（如 "_ext_${key}"）`);
		}
	}

	for (const field of schema.fields) {
		// 自动生成字段跳过所有校验（由系统填入）
		if (field.autoGenerated) continue;

		const value = fields[field.name];

		// 必填校验
		if (field.required && (value === undefined || value === null)) {
			errors.push(`字段 "${field.name}" 为必填项`);
			continue;
		}

		// 类型校验（跳过可选的空值）
		if (value !== undefined && value !== null) {
			const typeError = validateType(value, field);
			if (typeError) errors.push(typeError);
		}

		// 枚举校验
		if (field.enum && value !== undefined && value !== null && !field.enum.includes(String(value))) {
			errors.push(`字段 "${field.name}" 的值 "${value}" 不在允许范围内: ${field.enum.join(", ")}`);
		}
	}

	if (errors.length > 0) {
		throw new Error(`实例校验失败:\n${errors.map((e) => `  - ${e}`).join("\n")}`);
	}
}

function validateType(value: unknown, field: ConceptField): string | null {
	switch (field.type) {
		case "string":
			if (typeof value !== "string") {
				return `字段 "${field.name}" 应为字符串`;
			}
			break;
		case "number":
			if (typeof value !== "number") {
				return `字段 "${field.name}" 应为数字`;
			}
			break;
		case "boolean":
			if (typeof value !== "boolean") {
				return `字段 "${field.name}" 应为布尔值`;
			}
			break;
		case "date":
			if (typeof value !== "string" && typeof value !== "number") {
				return `字段 "${field.name}" 应为日期（ISO 字符串或时间戳）`;
			}
			break;
		case "array":
			if (!Array.isArray(value)) {
				return `字段 "${field.name}" 应为数组`;
			}
			break;
		case "object":
			if (typeof value !== "object" || Array.isArray(value) || value === null) {
				return `字段 "${field.name}" 应为对象`;
			}
			break;
		case "relation":
			// relation 字段值为关联实例 ID（字符串）或 ID 数组（1:N / N:M）
			if (typeof value !== "string" && !Array.isArray(value)) {
				return `字段 "${field.name}" 应为实例 ID（字符串）或实例 ID 数组`;
			}
			break;
	}
	return null;
}

export async function loadConceptSchema(
	ontologyId: string,
	conceptId: string
): Promise<ConceptSchema> {
	if (!isValidId(ontologyId) || !isValidId(conceptId)) {
		throw new Error("Invalid IDs: path traversal detected");
	}

	const filePath = schemaPath(ontologyId);
	const content = await fs.readFile(filePath, "utf-8");
	const ontology = JSON.parse(content) as {
		concepts?: Array<{
			id: string;
			name: string;
			domainId: string;
			attributes?: Record<string, { type: string; required?: boolean; description?: string; enum?: string[] }>;
		}>;
		domains?: Array<{ id: string }>;
		relations?: Array<{
			id: string;
			sourceId: string;
			targetId: string;
			type: string;
			cardinality?: string;
		}>;
		ontologyId?: string;
	};

	const concept = ontology.concepts?.find((c) => c.id === conceptId);
	if (!concept) {
		throw new Error(`概念 "${conceptId}" 在本体中不存在`);
	}

	// 普通属性字段（relation 类型的属性直接携带 relatedConceptId/relationType）
	const conceptMap = new Map((ontology.concepts ?? []).map((c) => [c.id, c.name]));
	const fields: ConceptField[] = Object.entries(concept.attributes ?? {}).map(([name, attr]) => {
		const base: ConceptField = {
			name,
			type: mapAttributeType(attr.type),
			required: attr.required ?? false,
			description: attr.description,
			enum: attr.enum,
			autoGenerated: (attr as Record<string, unknown>)["autoGenerated"] === true,
		};
		if (base.type === "relation") {
			const raw = attr as Record<string, unknown>;
			base.relatedConceptId = raw["relatedConceptId"] as string | undefined;
			base.relationType = raw["relationType"] as string | undefined;
			base.cardinality = raw["cardinality"] as ConceptField["cardinality"] | undefined;
			base.isReverse = false;
			if (base.relatedConceptId) {
				base.relatedConceptName = conceptMap.get(base.relatedConceptId);
			}
		}
		return base;
	});

	// 补充注入：本体 relations 中有但 attributes 里未定义的关系字段
	// 已在 attributes 中定义的 relation 字段（按 relatedConceptId+relationType 去重）
	const definedRelKeys = new Set(
		fields
			.filter((f) => f.type === "relation")
			.map((f) => `${f.relatedConceptId}__${f.relationType}__${f.isReverse ? "r" : "f"}`)
	);
	const usedNames = new Set(fields.map((f) => f.name));

	for (const rel of ontology.relations ?? []) {
		if (rel.sourceId === conceptId) {
			const key = `${rel.targetId}__${rel.type}__f`;
			if (definedRelKeys.has(key)) continue;
			const targetName = conceptMap.get(rel.targetId) ?? rel.targetId;
			let fieldName = targetName;
			if (usedNames.has(fieldName)) fieldName = `${targetName}（${rel.type}）`;
			fields.push({
				name: fieldName,
				type: "relation",
				required: false,
				description: attr_desc(rel.type, targetName, false),
				relatedConceptId: rel.targetId,
				relatedConceptName: targetName,
				relationType: rel.type,
				cardinality: (rel.cardinality as ConceptField["cardinality"]) ?? "N:M",
				isReverse: false,
			});
			usedNames.add(fieldName);
		} else if (rel.targetId === conceptId) {
			const key = `${rel.sourceId}__${rel.type}__r`;
			if (definedRelKeys.has(key)) continue;
			const sourceName = conceptMap.get(rel.sourceId) ?? rel.sourceId;
			let fieldName = sourceName;
			if (usedNames.has(fieldName)) fieldName = `${sourceName}（${rel.type} 反向）`;
			fields.push({
				name: fieldName,
				type: "relation",
				required: false,
				description: attr_desc(rel.type, sourceName, true),
				relatedConceptId: rel.sourceId,
				relatedConceptName: sourceName,
				relationType: rel.type,
				cardinality: (rel.cardinality as ConceptField["cardinality"]) ?? "N:M",
				isReverse: true,
			});
			usedNames.add(fieldName);
		}
	}

	return {
		conceptId: concept.id,
		domainId: concept.domainId,
		ontologyId: ontologyId,
		name: concept.name,
		fields,
	};
}

function attr_desc(relType: string, conceptName: string, isReverse: boolean): string {
	return isReverse ? `← ${conceptName}（${relType}）` : `→ ${conceptName}（${relType}）`;
}

function mapAttributeType(raw: string): ConceptField["type"] {
	switch (raw?.toLowerCase()) {
		case "string":
		case "text":
			return "string";
		case "number":
		case "int":
		case "float":
			return "number";
		case "boolean":
		case "bool":
			return "boolean";
		case "date":
		case "datetime":
			return "date";
		case "array":
		case "list":
			return "array";
		case "object":
		case "map":
			return "object";
		case "relation":
		case "reference":
		case "ref":
			return "relation";
		default:
			return "string";
	}
}
