/**
 * Ontology Data Store — 核心 CRUD 操作
 */

import fs from "fs/promises";
import { v4 as uuidv4 } from "uuid";
import { instanceDir, instancePath, isValidId } from "./config";
import { updateIndexEntry, removeIndexEntry, type IndexEntry } from "./index-manager";
import { validateInstance, loadConceptSchema } from "./schema-validator";
import type { InstanceData, InstanceMeta, ConceptSchema } from "./types";

async function ensureDir(dirPath: string): Promise<void> {
	await fs.mkdir(dirPath, { recursive: true });
}

function now(): number {
	return Date.now();
}

function generateId(): string {
	return `inst-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// ============================================================================
// Create
// ============================================================================

export async function createInstance(
	ontologyId: string,
	conceptId: string,
	fields: Record<string, unknown>,
	createdBy: "user" | "agent" | "skill" = "user",
	conceptSchema?: ConceptSchema
): Promise<InstanceData> {
	if (!isValidId(ontologyId) || !isValidId(conceptId)) {
		throw new Error("Invalid IDs: path traversal detected");
	}

	const schema = conceptSchema ?? (await loadConceptSchema(ontologyId, conceptId));

	// 自动注入 autoGenerated 字段（主键等），不需要上游传入
	const autoFields: Record<string, unknown> = {};
	for (const field of schema.fields) {
		if (field.autoGenerated && !(field.name in fields)) {
			autoFields[field.name] = uuidv4();
		}
	}
	const enrichedFields = { ...autoFields, ...fields };

	validateInstance(enrichedFields, schema);

	const id = generateId();
	const ts = now();
	const meta: InstanceMeta = {
		createdAt: ts,
		updatedAt: ts,
		createdBy,
		version: 1,
	};

	const instance: InstanceData = { id, conceptId, domainId: "", ontologyId, fields: enrichedFields, meta };

	const dir = instanceDir(ontologyId, conceptId);
	await ensureDir(dir);
	await fs.writeFile(instancePath(ontologyId, conceptId, id), JSON.stringify(instance, null, 2), "utf-8");

	const entry: IndexEntry = buildIndexEntry(instance);
	await updateIndexEntry(ontologyId, conceptId, id, entry);

	return instance;
}

// ============================================================================
// Read
// ============================================================================

export async function getInstance(
	ontologyId: string,
	conceptId: string,
	instanceId: string
): Promise<InstanceData> {
	const filePath = instancePath(ontologyId, conceptId, instanceId);
	const content = await fs.readFile(filePath, "utf-8");
	return JSON.parse(content) as InstanceData;
}

export async function listInstances(
	ontologyId: string,
	conceptId: string,
	ids: string[]
): Promise<InstanceData[]> {
	const results: InstanceData[] = [];
	for (const id of ids) {
		try {
			const instance = await getInstance(ontologyId, conceptId, id);
			results.push(instance);
		} catch {
			// 文件可能已被删除，跳过
		}
	}
	return results;
}

// ============================================================================
// Update
// ============================================================================

export async function updateInstance(
	ontologyId: string,
	conceptId: string,
	instanceId: string,
	fields: Record<string, unknown>,
	conceptSchema?: ConceptSchema
): Promise<InstanceData> {
	const filePath = instancePath(ontologyId, conceptId, instanceId);
	const content = await fs.readFile(filePath, "utf-8");
	const existing = JSON.parse(content) as InstanceData;

	const schema = conceptSchema ?? (await loadConceptSchema(ontologyId, conceptId));
	const mergedFields = { ...existing.fields, ...fields };
	validateInstance(mergedFields, schema);

	const updated: InstanceData = {
		...existing,
		fields: mergedFields,
		meta: { ...existing.meta, updatedAt: now(), version: existing.meta.version + 1 },
	};

	await fs.writeFile(filePath, JSON.stringify(updated, null, 2), "utf-8");

	const entry = buildIndexEntry(updated);
	await updateIndexEntry(ontologyId, conceptId, instanceId, entry);

	return updated;
}

// ============================================================================
// Delete
// ============================================================================

export async function deleteInstance(
	ontologyId: string,
	conceptId: string,
	instanceId: string
): Promise<void> {
	const filePath = instancePath(ontologyId, conceptId, instanceId);
	await fs.unlink(filePath);
	await removeIndexEntry(ontologyId, conceptId, instanceId);
}

// ============================================================================
// Helpers
// ============================================================================

function buildIndexEntry(instance: InstanceData): IndexEntry {
	return {
		...instance.fields,
		createdAt: instance.meta.createdAt,
		updatedAt: instance.meta.updatedAt,
	} as IndexEntry;
}
