/**
 * Ontology Data Store 类型定义
 */

import type { PaginationParams } from "../../../types/api";

// ============================================================================
// 实例数据
// ============================================================================

export interface InstanceData {
	id: string;
	conceptId: string;
	domainId: string;
	ontologyId: string;
	fields: Record<string, unknown>;
	meta: InstanceMeta;
}

export interface InstanceMeta {
	createdAt: number;
	updatedAt: number;
	createdBy: "user" | "agent" | "skill";
	version: number;
}

// ============================================================================
// 概念 Schema（用于校验和表单生成）
// ============================================================================

export interface ConceptSchema {
	conceptId: string;
	domainId: string;
	ontologyId: string;
	name: string;
	fields: ConceptField[];
}

export interface ConceptField {
	name: string;
	type: "string" | "number" | "boolean" | "date" | "array" | "object" | "relation";
	required: boolean;
	defaultValue?: unknown;
	description?: string;
	/** 枚举值（下拉选项） */
	enum?: string[];
	/** relation 类型专用：关联概念 ID */
	relatedConceptId?: string;
	/** relation 类型专用：关联概念名称（展示用） */
	relatedConceptName?: string;
	/** relation 类型专用：关系类型名称（如 belongs_to） */
	relationType?: string;
	/** relation 类型专用：基数约束 */
	cardinality?: "1:1" | "1:N" | "N:1" | "N:M";
	/** relation 类型专用：是否为反向关系（本概念为 target） */
	isReverse?: boolean;
	/** 自动生成字段（如主键），创建时由系统填入，不需要上游传入 */
	autoGenerated?: boolean;
}

export interface InstanceRelation {
	id: string;
	sourceInstanceId: string;
	targetInstanceId: string;
	type: string;
	sourceConceptId: string;
	targetConceptId: string;
}

export interface InstanceRelationsData {
	relations: InstanceRelation[];
}

// ============================================================================
// 索引结构
// ============================================================================

export interface IndexEntry {
	/** 索引摘要，包含常用查询字段 */
	[field: string]: unknown;
}

export interface IndexData {
	conceptId: string;
	updatedAt: number;
	entries: Record<string, IndexEntry>;
}

// ============================================================================
// 查询
// ============================================================================

export interface QueryFilters {
	/** 字段过滤: { field: value } 精确匹配 */
	[key: string]: unknown;
}

export interface QueryParams extends PaginationParams {
	filters?: QueryFilters;
}

export interface QueryResult {
	items: InstanceData[];
	total: number;
	page: number;
	limit: number;
	totalPages: number;
}

// ============================================================================
// 版本
// ============================================================================

export interface VersionSnapshot {
	version: number;
	instanceId: string;
	label?: string;
	savedAt: number;
	data: InstanceData;
}

// ============================================================================
// 批量删除
// ============================================================================

export interface BatchDeletePreview {
	count: number;
	ids: string[];
}

export interface BatchDeleteResult {
	deleted: string[];
	failed: Array<{ id: string; reason: string }>;
}

// ============================================================================
// 导出
// ============================================================================

export type ExportFormat = "json" | "csv";

export interface ExportOptions {
	format: ExportFormat;
	conceptId: string;
	domainId?: string;
	ontologyId: string;
	fields?: string[];
}
