"use strict";
/**
 * Ontology Data Store — 核心 CRUD 操作
 */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createInstance = createInstance;
exports.getInstance = getInstance;
exports.listInstances = listInstances;
exports.updateInstance = updateInstance;
exports.deleteInstance = deleteInstance;
const promises_1 = __importDefault(require("fs/promises"));
const uuid_1 = require("uuid");
const config_1 = require("./config");
const index_manager_1 = require("./index-manager");
const schema_validator_1 = require("./schema-validator");
async function ensureDir(dirPath) {
    await promises_1.default.mkdir(dirPath, { recursive: true });
}
function now() {
    return Date.now();
}
function generateId() {
    return `inst-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}
// ============================================================================
// Create
// ============================================================================
async function createInstance(ontologyId, conceptId, fields, createdBy = "user", conceptSchema) {
    if (!(0, config_1.isValidId)(ontologyId) || !(0, config_1.isValidId)(conceptId)) {
        throw new Error("Invalid IDs: path traversal detected");
    }
    const schema = conceptSchema ?? (await (0, schema_validator_1.loadConceptSchema)(ontologyId, conceptId));
    // 自动注入 autoGenerated 字段（主键等），不需要上游传入
    const autoFields = {};
    for (const field of schema.fields) {
        if (field.autoGenerated && !(field.name in fields)) {
            autoFields[field.name] = (0, uuid_1.v4)();
        }
    }
    const enrichedFields = { ...autoFields, ...fields };
    (0, schema_validator_1.validateInstance)(enrichedFields, schema);
    const id = generateId();
    const ts = now();
    const meta = {
        createdAt: ts,
        updatedAt: ts,
        createdBy,
        version: 1,
    };
    const instance = { id, conceptId, domainId: "", ontologyId, fields: enrichedFields, meta };
    const dir = (0, config_1.instanceDir)(ontologyId, conceptId);
    await ensureDir(dir);
    await promises_1.default.writeFile((0, config_1.instancePath)(ontologyId, conceptId, id), JSON.stringify(instance, null, 2), "utf-8");
    const entry = buildIndexEntry(instance);
    await (0, index_manager_1.updateIndexEntry)(ontologyId, conceptId, id, entry);
    return instance;
}
// ============================================================================
// Read
// ============================================================================
async function getInstance(ontologyId, conceptId, instanceId) {
    const filePath = (0, config_1.instancePath)(ontologyId, conceptId, instanceId);
    const content = await promises_1.default.readFile(filePath, "utf-8");
    return JSON.parse(content);
}
async function listInstances(ontologyId, conceptId, ids) {
    const results = [];
    for (const id of ids) {
        try {
            const instance = await getInstance(ontologyId, conceptId, id);
            results.push(instance);
        }
        catch {
            // 文件可能已被删除，跳过
        }
    }
    return results;
}
// ============================================================================
// Update
// ============================================================================
async function updateInstance(ontologyId, conceptId, instanceId, fields, conceptSchema) {
    const filePath = (0, config_1.instancePath)(ontologyId, conceptId, instanceId);
    const content = await promises_1.default.readFile(filePath, "utf-8");
    const existing = JSON.parse(content);
    const schema = conceptSchema ?? (await (0, schema_validator_1.loadConceptSchema)(ontologyId, conceptId));
    const mergedFields = { ...existing.fields, ...fields };
    (0, schema_validator_1.validateInstance)(mergedFields, schema);
    const updated = {
        ...existing,
        fields: mergedFields,
        meta: { ...existing.meta, updatedAt: now(), version: existing.meta.version + 1 },
    };
    await promises_1.default.writeFile(filePath, JSON.stringify(updated, null, 2), "utf-8");
    const entry = buildIndexEntry(updated);
    await (0, index_manager_1.updateIndexEntry)(ontologyId, conceptId, instanceId, entry);
    return updated;
}
// ============================================================================
// Delete
// ============================================================================
async function deleteInstance(ontologyId, conceptId, instanceId) {
    const filePath = (0, config_1.instancePath)(ontologyId, conceptId, instanceId);
    await promises_1.default.unlink(filePath);
    await (0, index_manager_1.removeIndexEntry)(ontologyId, conceptId, instanceId);
}
// ============================================================================
// Helpers
// ============================================================================
function buildIndexEntry(instance) {
    return {
        ...instance.fields,
        createdAt: instance.meta.createdAt,
        updatedAt: instance.meta.updatedAt,
    };
}
